-- FUNCTION CREATED UNDER NAME SafeDiv
-- DIVIDE 2 NUMBER AND RETURN THE RESULT OR 0
DELIMITER $$

CREATE FUNCTION SafeDiv (a INT, b INT)
RETURNS FLOAT DETERMINISTIC
BEGIN
	DECLARE result FLOAT DEFAULT 0;
	IF b = 0 THEN
		SET result = 0;
	ELSE
		SET result = a / b;
	END IF;
	RETURN result;
END $$
DELIMITER ;
