-- TRIGGER NAMED REMOVE ORDERED
-- WHEN ORDER IS SET WE REMOVE FROM ITEM STOCK TABLE
DELIMITER $$
CREATE TRIGGER remove_ordered BEFORE INSERT ON orders
FOR EACH ROW
BEGIN
	UPDATE items
	SET quantity = quantity -NEW.number
	WHERE name = NEW.item_name;
END;
$$
DELIMITER ;
